version: '3.4'

services:
    dev_database:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: dev-admin-user
            POSTGRES_PASSWORD: dev-admin-password
            POSTGRES_DB: dev-family-hub-server
        ports:
            - '5432:5432'
